<?php
include('header.php');
include('./partialfiles/_banner.php');
include('./partialfiles/_about.php');
include('./partialfiles/_manosarygrid.php');
include('./partialfiles/_questionbx.php');
include('./partialfiles/_services.php');
include('./partialfiles/_careers.php');
include('./partialfiles/_contact.php');
include('./partialfiles/_join.php');
include('footer.php')
?>